---
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
    working_directory: ~/singnet/snet-sdk-js
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Trigger platform-pipeline build
          command: |
            if [ "$CIRCLE_BRANCH" == "$TRIGGER_BUILD_BRANCH" ]
            then
              curl -u ${CIRCLECI_PLATFORM_PIPELINE_TOKEN}: \
                -d build_parameters[CIRCLE_JOB]=build \
                -d build_parameters[PARENT_PROJECT_REPONAME]="$CIRCLE_PROJECT_REPONAME" \
                -d build_parameters[PARENT_BRANCH]="$CIRCLE_BRANCH" \
                -d build_parameters[PARENT_BUILD_URL]="$CIRCLE_BUILD_URL" \
                https://circleci.com/api/v1.1/project/github/singnet/platform-pipeline/tree/${TRIGGER_BUILD_BRANCH}
            fi
