// source: training_daemon.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_descriptor_pb = require('google-protobuf/google/protobuf/descriptor_pb.js');
goog.object.extend(proto, google_protobuf_descriptor_pb);
var google_protobuf_struct_pb = require('google-protobuf/google/protobuf/struct_pb.js');
goog.object.extend(proto, google_protobuf_struct_pb);
var training_pb = require('./training_pb.js');
goog.object.extend(proto, training_pb);
var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
goog.exportSymbol('proto.training.AllModelsRequest', null, global);
goog.exportSymbol('proto.training.AuthValidateRequest', null, global);
goog.exportSymbol('proto.training.AuthorizationDetails', null, global);
goog.exportSymbol('proto.training.CommonRequest', null, global);
goog.exportSymbol('proto.training.MethodMetadata', null, global);
goog.exportSymbol('proto.training.MethodMetadataRequest', null, global);
goog.exportSymbol('proto.training.ModelsResponse', null, global);
goog.exportSymbol('proto.training.NewModelRequest', null, global);
goog.exportSymbol('proto.training.TrainingMetadata', null, global);
goog.exportSymbol('proto.training.UpdateModelRequest', null, global);
goog.exportSymbol('proto.training.UploadAndValidateRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.training.AuthorizationDetails = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.training.AuthorizationDetails, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.training.AuthorizationDetails.displayName = 'proto.training.AuthorizationDetails';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.training.NewModelRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.training.NewModelRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.training.NewModelRequest.displayName = 'proto.training.NewModelRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.training.AuthValidateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.training.AuthValidateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.training.AuthValidateRequest.displayName = 'proto.training.AuthValidateRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.training.UploadAndValidateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.training.UploadAndValidateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.training.UploadAndValidateRequest.displayName = 'proto.training.UploadAndValidateRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.training.CommonRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.training.CommonRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.training.CommonRequest.displayName = 'proto.training.CommonRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.training.UpdateModelRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.training.UpdateModelRequest.repeatedFields_, null);
};
goog.inherits(proto.training.UpdateModelRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.training.UpdateModelRequest.displayName = 'proto.training.UpdateModelRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.training.ModelsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.training.ModelsResponse.repeatedFields_, null);
};
goog.inherits(proto.training.ModelsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.training.ModelsResponse.displayName = 'proto.training.ModelsResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.training.MethodMetadataRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.training.MethodMetadataRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.training.MethodMetadataRequest.displayName = 'proto.training.MethodMetadataRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.training.AllModelsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.training.AllModelsRequest.repeatedFields_, null);
};
goog.inherits(proto.training.AllModelsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.training.AllModelsRequest.displayName = 'proto.training.AllModelsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.training.TrainingMetadata = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.training.TrainingMetadata, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.training.TrainingMetadata.displayName = 'proto.training.TrainingMetadata';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.training.MethodMetadata = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, null, null);
};
goog.inherits(proto.training.MethodMetadata, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.training.MethodMetadata.displayName = 'proto.training.MethodMetadata';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.training.AuthorizationDetails.prototype.toObject = function(opt_includeInstance) {
  return proto.training.AuthorizationDetails.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.training.AuthorizationDetails} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.training.AuthorizationDetails.toObject = function(includeInstance, msg) {
  var f, obj = {
    currentBlock: jspb.Message.getFieldWithDefault(msg, 1, 0),
    message: jspb.Message.getFieldWithDefault(msg, 2, ""),
    signature: msg.getSignature_asB64(),
    signerAddress: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.training.AuthorizationDetails}
 */
proto.training.AuthorizationDetails.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.training.AuthorizationDetails;
  return proto.training.AuthorizationDetails.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.training.AuthorizationDetails} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.training.AuthorizationDetails}
 */
proto.training.AuthorizationDetails.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCurrentBlock(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSignature(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setSignerAddress(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.training.AuthorizationDetails.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.training.AuthorizationDetails.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.training.AuthorizationDetails} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.training.AuthorizationDetails.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCurrentBlock();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSignature_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getSignerAddress();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional uint64 current_block = 1;
 * @return {number}
 */
proto.training.AuthorizationDetails.prototype.getCurrentBlock = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.training.AuthorizationDetails} returns this
 */
proto.training.AuthorizationDetails.prototype.setCurrentBlock = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.training.AuthorizationDetails.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.training.AuthorizationDetails} returns this
 */
proto.training.AuthorizationDetails.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bytes signature = 3;
 * @return {!(string|Uint8Array)}
 */
proto.training.AuthorizationDetails.prototype.getSignature = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes signature = 3;
 * This is a type-conversion wrapper around `getSignature()`
 * @return {string}
 */
proto.training.AuthorizationDetails.prototype.getSignature_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSignature()));
};


/**
 * optional bytes signature = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSignature()`
 * @return {!Uint8Array}
 */
proto.training.AuthorizationDetails.prototype.getSignature_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSignature()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.training.AuthorizationDetails} returns this
 */
proto.training.AuthorizationDetails.prototype.setSignature = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional string signer_address = 4;
 * @return {string}
 */
proto.training.AuthorizationDetails.prototype.getSignerAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.training.AuthorizationDetails} returns this
 */
proto.training.AuthorizationDetails.prototype.setSignerAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.training.NewModelRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.training.NewModelRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.training.NewModelRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.training.NewModelRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    authorization: (f = msg.getAuthorization()) && proto.training.AuthorizationDetails.toObject(includeInstance, f),
    model: (f = msg.getModel()) && training_pb.NewModel.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.training.NewModelRequest}
 */
proto.training.NewModelRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.training.NewModelRequest;
  return proto.training.NewModelRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.training.NewModelRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.training.NewModelRequest}
 */
proto.training.NewModelRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.training.AuthorizationDetails;
      reader.readMessage(value,proto.training.AuthorizationDetails.deserializeBinaryFromReader);
      msg.setAuthorization(value);
      break;
    case 2:
      var value = new training_pb.NewModel;
      reader.readMessage(value,training_pb.NewModel.deserializeBinaryFromReader);
      msg.setModel(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.training.NewModelRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.training.NewModelRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.training.NewModelRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.training.NewModelRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAuthorization();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.training.AuthorizationDetails.serializeBinaryToWriter
    );
  }
  f = message.getModel();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      training_pb.NewModel.serializeBinaryToWriter
    );
  }
};


/**
 * optional AuthorizationDetails authorization = 1;
 * @return {?proto.training.AuthorizationDetails}
 */
proto.training.NewModelRequest.prototype.getAuthorization = function() {
  return /** @type{?proto.training.AuthorizationDetails} */ (
    jspb.Message.getWrapperField(this, proto.training.AuthorizationDetails, 1));
};


/**
 * @param {?proto.training.AuthorizationDetails|undefined} value
 * @return {!proto.training.NewModelRequest} returns this
*/
proto.training.NewModelRequest.prototype.setAuthorization = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.training.NewModelRequest} returns this
 */
proto.training.NewModelRequest.prototype.clearAuthorization = function() {
  return this.setAuthorization(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.training.NewModelRequest.prototype.hasAuthorization = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional NewModel model = 2;
 * @return {?proto.training.NewModel}
 */
proto.training.NewModelRequest.prototype.getModel = function() {
  return /** @type{?proto.training.NewModel} */ (
    jspb.Message.getWrapperField(this, training_pb.NewModel, 2));
};


/**
 * @param {?proto.training.NewModel|undefined} value
 * @return {!proto.training.NewModelRequest} returns this
*/
proto.training.NewModelRequest.prototype.setModel = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.training.NewModelRequest} returns this
 */
proto.training.NewModelRequest.prototype.clearModel = function() {
  return this.setModel(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.training.NewModelRequest.prototype.hasModel = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.training.AuthValidateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.training.AuthValidateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.training.AuthValidateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.training.AuthValidateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    authorization: (f = msg.getAuthorization()) && proto.training.AuthorizationDetails.toObject(includeInstance, f),
    modelId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    trainingDataLink: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.training.AuthValidateRequest}
 */
proto.training.AuthValidateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.training.AuthValidateRequest;
  return proto.training.AuthValidateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.training.AuthValidateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.training.AuthValidateRequest}
 */
proto.training.AuthValidateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.training.AuthorizationDetails;
      reader.readMessage(value,proto.training.AuthorizationDetails.deserializeBinaryFromReader);
      msg.setAuthorization(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setModelId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTrainingDataLink(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.training.AuthValidateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.training.AuthValidateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.training.AuthValidateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.training.AuthValidateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAuthorization();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.training.AuthorizationDetails.serializeBinaryToWriter
    );
  }
  f = message.getModelId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTrainingDataLink();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional AuthorizationDetails authorization = 1;
 * @return {?proto.training.AuthorizationDetails}
 */
proto.training.AuthValidateRequest.prototype.getAuthorization = function() {
  return /** @type{?proto.training.AuthorizationDetails} */ (
    jspb.Message.getWrapperField(this, proto.training.AuthorizationDetails, 1));
};


/**
 * @param {?proto.training.AuthorizationDetails|undefined} value
 * @return {!proto.training.AuthValidateRequest} returns this
*/
proto.training.AuthValidateRequest.prototype.setAuthorization = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.training.AuthValidateRequest} returns this
 */
proto.training.AuthValidateRequest.prototype.clearAuthorization = function() {
  return this.setAuthorization(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.training.AuthValidateRequest.prototype.hasAuthorization = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string model_id = 2;
 * @return {string}
 */
proto.training.AuthValidateRequest.prototype.getModelId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.training.AuthValidateRequest} returns this
 */
proto.training.AuthValidateRequest.prototype.setModelId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string training_data_link = 3;
 * @return {string}
 */
proto.training.AuthValidateRequest.prototype.getTrainingDataLink = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.training.AuthValidateRequest} returns this
 */
proto.training.AuthValidateRequest.prototype.setTrainingDataLink = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.training.UploadAndValidateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.training.UploadAndValidateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.training.UploadAndValidateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.training.UploadAndValidateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    authorization: (f = msg.getAuthorization()) && proto.training.AuthorizationDetails.toObject(includeInstance, f),
    uploadInput: (f = msg.getUploadInput()) && training_pb.UploadInput.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.training.UploadAndValidateRequest}
 */
proto.training.UploadAndValidateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.training.UploadAndValidateRequest;
  return proto.training.UploadAndValidateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.training.UploadAndValidateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.training.UploadAndValidateRequest}
 */
proto.training.UploadAndValidateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.training.AuthorizationDetails;
      reader.readMessage(value,proto.training.AuthorizationDetails.deserializeBinaryFromReader);
      msg.setAuthorization(value);
      break;
    case 2:
      var value = new training_pb.UploadInput;
      reader.readMessage(value,training_pb.UploadInput.deserializeBinaryFromReader);
      msg.setUploadInput(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.training.UploadAndValidateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.training.UploadAndValidateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.training.UploadAndValidateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.training.UploadAndValidateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAuthorization();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.training.AuthorizationDetails.serializeBinaryToWriter
    );
  }
  f = message.getUploadInput();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      training_pb.UploadInput.serializeBinaryToWriter
    );
  }
};


/**
 * optional AuthorizationDetails authorization = 1;
 * @return {?proto.training.AuthorizationDetails}
 */
proto.training.UploadAndValidateRequest.prototype.getAuthorization = function() {
  return /** @type{?proto.training.AuthorizationDetails} */ (
    jspb.Message.getWrapperField(this, proto.training.AuthorizationDetails, 1));
};


/**
 * @param {?proto.training.AuthorizationDetails|undefined} value
 * @return {!proto.training.UploadAndValidateRequest} returns this
*/
proto.training.UploadAndValidateRequest.prototype.setAuthorization = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.training.UploadAndValidateRequest} returns this
 */
proto.training.UploadAndValidateRequest.prototype.clearAuthorization = function() {
  return this.setAuthorization(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.training.UploadAndValidateRequest.prototype.hasAuthorization = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional UploadInput upload_input = 2;
 * @return {?proto.training.UploadInput}
 */
proto.training.UploadAndValidateRequest.prototype.getUploadInput = function() {
  return /** @type{?proto.training.UploadInput} */ (
    jspb.Message.getWrapperField(this, training_pb.UploadInput, 2));
};


/**
 * @param {?proto.training.UploadInput|undefined} value
 * @return {!proto.training.UploadAndValidateRequest} returns this
*/
proto.training.UploadAndValidateRequest.prototype.setUploadInput = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.training.UploadAndValidateRequest} returns this
 */
proto.training.UploadAndValidateRequest.prototype.clearUploadInput = function() {
  return this.setUploadInput(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.training.UploadAndValidateRequest.prototype.hasUploadInput = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.training.CommonRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.training.CommonRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.training.CommonRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.training.CommonRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    authorization: (f = msg.getAuthorization()) && proto.training.AuthorizationDetails.toObject(includeInstance, f),
    modelId: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.training.CommonRequest}
 */
proto.training.CommonRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.training.CommonRequest;
  return proto.training.CommonRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.training.CommonRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.training.CommonRequest}
 */
proto.training.CommonRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.training.AuthorizationDetails;
      reader.readMessage(value,proto.training.AuthorizationDetails.deserializeBinaryFromReader);
      msg.setAuthorization(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setModelId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.training.CommonRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.training.CommonRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.training.CommonRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.training.CommonRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAuthorization();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.training.AuthorizationDetails.serializeBinaryToWriter
    );
  }
  f = message.getModelId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional AuthorizationDetails authorization = 1;
 * @return {?proto.training.AuthorizationDetails}
 */
proto.training.CommonRequest.prototype.getAuthorization = function() {
  return /** @type{?proto.training.AuthorizationDetails} */ (
    jspb.Message.getWrapperField(this, proto.training.AuthorizationDetails, 1));
};


/**
 * @param {?proto.training.AuthorizationDetails|undefined} value
 * @return {!proto.training.CommonRequest} returns this
*/
proto.training.CommonRequest.prototype.setAuthorization = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.training.CommonRequest} returns this
 */
proto.training.CommonRequest.prototype.clearAuthorization = function() {
  return this.setAuthorization(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.training.CommonRequest.prototype.hasAuthorization = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string model_id = 2;
 * @return {string}
 */
proto.training.CommonRequest.prototype.getModelId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.training.CommonRequest} returns this
 */
proto.training.CommonRequest.prototype.setModelId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.training.UpdateModelRequest.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.training.UpdateModelRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.training.UpdateModelRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.training.UpdateModelRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.training.UpdateModelRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    authorization: (f = msg.getAuthorization()) && proto.training.AuthorizationDetails.toObject(includeInstance, f),
    modelId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    modelName: jspb.Message.getFieldWithDefault(msg, 3, ""),
    description: jspb.Message.getFieldWithDefault(msg, 4, ""),
    addressListList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.training.UpdateModelRequest}
 */
proto.training.UpdateModelRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.training.UpdateModelRequest;
  return proto.training.UpdateModelRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.training.UpdateModelRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.training.UpdateModelRequest}
 */
proto.training.UpdateModelRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.training.AuthorizationDetails;
      reader.readMessage(value,proto.training.AuthorizationDetails.deserializeBinaryFromReader);
      msg.setAuthorization(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setModelId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setModelName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addAddressList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.training.UpdateModelRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.training.UpdateModelRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.training.UpdateModelRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.training.UpdateModelRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAuthorization();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.training.AuthorizationDetails.serializeBinaryToWriter
    );
  }
  f = message.getModelId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getAddressListList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
};


/**
 * optional AuthorizationDetails authorization = 1;
 * @return {?proto.training.AuthorizationDetails}
 */
proto.training.UpdateModelRequest.prototype.getAuthorization = function() {
  return /** @type{?proto.training.AuthorizationDetails} */ (
    jspb.Message.getWrapperField(this, proto.training.AuthorizationDetails, 1));
};


/**
 * @param {?proto.training.AuthorizationDetails|undefined} value
 * @return {!proto.training.UpdateModelRequest} returns this
*/
proto.training.UpdateModelRequest.prototype.setAuthorization = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.training.UpdateModelRequest} returns this
 */
proto.training.UpdateModelRequest.prototype.clearAuthorization = function() {
  return this.setAuthorization(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.training.UpdateModelRequest.prototype.hasAuthorization = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string model_id = 2;
 * @return {string}
 */
proto.training.UpdateModelRequest.prototype.getModelId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.training.UpdateModelRequest} returns this
 */
proto.training.UpdateModelRequest.prototype.setModelId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string model_name = 3;
 * @return {string}
 */
proto.training.UpdateModelRequest.prototype.getModelName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.training.UpdateModelRequest} returns this
 */
proto.training.UpdateModelRequest.prototype.setModelName = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.training.UpdateModelRequest} returns this
 */
proto.training.UpdateModelRequest.prototype.clearModelName = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.training.UpdateModelRequest.prototype.hasModelName = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string description = 4;
 * @return {string}
 */
proto.training.UpdateModelRequest.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.training.UpdateModelRequest} returns this
 */
proto.training.UpdateModelRequest.prototype.setDescription = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.training.UpdateModelRequest} returns this
 */
proto.training.UpdateModelRequest.prototype.clearDescription = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.training.UpdateModelRequest.prototype.hasDescription = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated string address_list = 5;
 * @return {!Array<string>}
 */
proto.training.UpdateModelRequest.prototype.getAddressListList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.training.UpdateModelRequest} returns this
 */
proto.training.UpdateModelRequest.prototype.setAddressListList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.training.UpdateModelRequest} returns this
 */
proto.training.UpdateModelRequest.prototype.addAddressList = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.training.UpdateModelRequest} returns this
 */
proto.training.UpdateModelRequest.prototype.clearAddressListList = function() {
  return this.setAddressListList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.training.ModelsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.training.ModelsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.training.ModelsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.training.ModelsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.training.ModelsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    listOfModelsList: jspb.Message.toObjectList(msg.getListOfModelsList(),
    training_pb.ModelResponse.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.training.ModelsResponse}
 */
proto.training.ModelsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.training.ModelsResponse;
  return proto.training.ModelsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.training.ModelsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.training.ModelsResponse}
 */
proto.training.ModelsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new training_pb.ModelResponse;
      reader.readMessage(value,training_pb.ModelResponse.deserializeBinaryFromReader);
      msg.addListOfModels(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.training.ModelsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.training.ModelsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.training.ModelsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.training.ModelsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getListOfModelsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      training_pb.ModelResponse.serializeBinaryToWriter
    );
  }
};


/**
 * repeated ModelResponse list_of_models = 1;
 * @return {!Array<!proto.training.ModelResponse>}
 */
proto.training.ModelsResponse.prototype.getListOfModelsList = function() {
  return /** @type{!Array<!proto.training.ModelResponse>} */ (
    jspb.Message.getRepeatedWrapperField(this, training_pb.ModelResponse, 1));
};


/**
 * @param {!Array<!proto.training.ModelResponse>} value
 * @return {!proto.training.ModelsResponse} returns this
*/
proto.training.ModelsResponse.prototype.setListOfModelsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.training.ModelResponse=} opt_value
 * @param {number=} opt_index
 * @return {!proto.training.ModelResponse}
 */
proto.training.ModelsResponse.prototype.addListOfModels = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.training.ModelResponse, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.training.ModelsResponse} returns this
 */
proto.training.ModelsResponse.prototype.clearListOfModelsList = function() {
  return this.setListOfModelsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.training.MethodMetadataRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.training.MethodMetadataRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.training.MethodMetadataRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.training.MethodMetadataRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    modelId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    grpcMethodName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    grpcServiceName: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.training.MethodMetadataRequest}
 */
proto.training.MethodMetadataRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.training.MethodMetadataRequest;
  return proto.training.MethodMetadataRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.training.MethodMetadataRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.training.MethodMetadataRequest}
 */
proto.training.MethodMetadataRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setModelId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setGrpcMethodName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setGrpcServiceName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.training.MethodMetadataRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.training.MethodMetadataRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.training.MethodMetadataRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.training.MethodMetadataRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getModelId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getGrpcMethodName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getGrpcServiceName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string model_id = 1;
 * @return {string}
 */
proto.training.MethodMetadataRequest.prototype.getModelId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.training.MethodMetadataRequest} returns this
 */
proto.training.MethodMetadataRequest.prototype.setModelId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string grpc_method_name = 2;
 * @return {string}
 */
proto.training.MethodMetadataRequest.prototype.getGrpcMethodName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.training.MethodMetadataRequest} returns this
 */
proto.training.MethodMetadataRequest.prototype.setGrpcMethodName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string grpc_service_name = 3;
 * @return {string}
 */
proto.training.MethodMetadataRequest.prototype.getGrpcServiceName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.training.MethodMetadataRequest} returns this
 */
proto.training.MethodMetadataRequest.prototype.setGrpcServiceName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.training.AllModelsRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.training.AllModelsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.training.AllModelsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.training.AllModelsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.training.AllModelsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    authorization: (f = msg.getAuthorization()) && proto.training.AuthorizationDetails.toObject(includeInstance, f),
    statusesList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    isPublic: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    grpcMethodName: jspb.Message.getFieldWithDefault(msg, 5, ""),
    grpcServiceName: jspb.Message.getFieldWithDefault(msg, 6, ""),
    name: jspb.Message.getFieldWithDefault(msg, 7, ""),
    createdByAddress: jspb.Message.getFieldWithDefault(msg, 8, ""),
    pageSize: jspb.Message.getFieldWithDefault(msg, 9, 0),
    page: jspb.Message.getFieldWithDefault(msg, 10, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.training.AllModelsRequest}
 */
proto.training.AllModelsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.training.AllModelsRequest;
  return proto.training.AllModelsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.training.AllModelsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.training.AllModelsRequest}
 */
proto.training.AllModelsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.training.AuthorizationDetails;
      reader.readMessage(value,proto.training.AuthorizationDetails.deserializeBinaryFromReader);
      msg.setAuthorization(value);
      break;
    case 3:
      var values = /** @type {!Array<!proto.training.Status>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addStatuses(values[i]);
      }
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsPublic(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setGrpcMethodName(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setGrpcServiceName(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreatedByAddress(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setPageSize(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setPage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.training.AllModelsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.training.AllModelsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.training.AllModelsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.training.AllModelsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAuthorization();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.training.AuthorizationDetails.serializeBinaryToWriter
    );
  }
  f = message.getStatusesList();
  if (f.length > 0) {
    writer.writePackedEnum(
      3,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getGrpcMethodName();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getGrpcServiceName();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getCreatedByAddress();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getPageSize();
  if (f !== 0) {
    writer.writeUint64(
      9,
      f
    );
  }
  f = message.getPage();
  if (f !== 0) {
    writer.writeUint64(
      10,
      f
    );
  }
};


/**
 * optional AuthorizationDetails authorization = 1;
 * @return {?proto.training.AuthorizationDetails}
 */
proto.training.AllModelsRequest.prototype.getAuthorization = function() {
  return /** @type{?proto.training.AuthorizationDetails} */ (
    jspb.Message.getWrapperField(this, proto.training.AuthorizationDetails, 1));
};


/**
 * @param {?proto.training.AuthorizationDetails|undefined} value
 * @return {!proto.training.AllModelsRequest} returns this
*/
proto.training.AllModelsRequest.prototype.setAuthorization = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.training.AllModelsRequest} returns this
 */
proto.training.AllModelsRequest.prototype.clearAuthorization = function() {
  return this.setAuthorization(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.training.AllModelsRequest.prototype.hasAuthorization = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Status statuses = 3;
 * @return {!Array<!proto.training.Status>}
 */
proto.training.AllModelsRequest.prototype.getStatusesList = function() {
  return /** @type {!Array<!proto.training.Status>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<!proto.training.Status>} value
 * @return {!proto.training.AllModelsRequest} returns this
 */
proto.training.AllModelsRequest.prototype.setStatusesList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {!proto.training.Status} value
 * @param {number=} opt_index
 * @return {!proto.training.AllModelsRequest} returns this
 */
proto.training.AllModelsRequest.prototype.addStatuses = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.training.AllModelsRequest} returns this
 */
proto.training.AllModelsRequest.prototype.clearStatusesList = function() {
  return this.setStatusesList([]);
};


/**
 * optional bool is_public = 4;
 * @return {boolean}
 */
proto.training.AllModelsRequest.prototype.getIsPublic = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.training.AllModelsRequest} returns this
 */
proto.training.AllModelsRequest.prototype.setIsPublic = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.training.AllModelsRequest} returns this
 */
proto.training.AllModelsRequest.prototype.clearIsPublic = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.training.AllModelsRequest.prototype.hasIsPublic = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string grpc_method_name = 5;
 * @return {string}
 */
proto.training.AllModelsRequest.prototype.getGrpcMethodName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.training.AllModelsRequest} returns this
 */
proto.training.AllModelsRequest.prototype.setGrpcMethodName = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string grpc_service_name = 6;
 * @return {string}
 */
proto.training.AllModelsRequest.prototype.getGrpcServiceName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.training.AllModelsRequest} returns this
 */
proto.training.AllModelsRequest.prototype.setGrpcServiceName = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string name = 7;
 * @return {string}
 */
proto.training.AllModelsRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.training.AllModelsRequest} returns this
 */
proto.training.AllModelsRequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string created_by_address = 8;
 * @return {string}
 */
proto.training.AllModelsRequest.prototype.getCreatedByAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.training.AllModelsRequest} returns this
 */
proto.training.AllModelsRequest.prototype.setCreatedByAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional uint64 page_size = 9;
 * @return {number}
 */
proto.training.AllModelsRequest.prototype.getPageSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.training.AllModelsRequest} returns this
 */
proto.training.AllModelsRequest.prototype.setPageSize = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional uint64 page = 10;
 * @return {number}
 */
proto.training.AllModelsRequest.prototype.getPage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.training.AllModelsRequest} returns this
 */
proto.training.AllModelsRequest.prototype.setPage = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.training.TrainingMetadata.prototype.toObject = function(opt_includeInstance) {
  return proto.training.TrainingMetadata.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.training.TrainingMetadata} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.training.TrainingMetadata.toObject = function(includeInstance, msg) {
  var f, obj = {
    trainingenabled: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    traininginproto: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    trainingmethodsMap: (f = msg.getTrainingmethodsMap()) ? f.toObject(includeInstance, proto.google.protobuf.ListValue.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.training.TrainingMetadata}
 */
proto.training.TrainingMetadata.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.training.TrainingMetadata;
  return proto.training.TrainingMetadata.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.training.TrainingMetadata} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.training.TrainingMetadata}
 */
proto.training.TrainingMetadata.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTrainingenabled(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTraininginproto(value);
      break;
    case 3:
      var value = msg.getTrainingmethodsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.google.protobuf.ListValue.deserializeBinaryFromReader, "", new proto.google.protobuf.ListValue());
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.training.TrainingMetadata.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.training.TrainingMetadata.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.training.TrainingMetadata} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.training.TrainingMetadata.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTrainingenabled();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getTraininginproto();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getTrainingmethodsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(3, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.google.protobuf.ListValue.serializeBinaryToWriter);
  }
};


/**
 * optional bool trainingEnabled = 1;
 * @return {boolean}
 */
proto.training.TrainingMetadata.prototype.getTrainingenabled = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.training.TrainingMetadata} returns this
 */
proto.training.TrainingMetadata.prototype.setTrainingenabled = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional bool trainingInProto = 2;
 * @return {boolean}
 */
proto.training.TrainingMetadata.prototype.getTraininginproto = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.training.TrainingMetadata} returns this
 */
proto.training.TrainingMetadata.prototype.setTraininginproto = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * map<string, google.protobuf.ListValue> trainingMethods = 3;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.google.protobuf.ListValue>}
 */
proto.training.TrainingMetadata.prototype.getTrainingmethodsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.google.protobuf.ListValue>} */ (
      jspb.Message.getMapField(this, 3, opt_noLazyCreate,
      proto.google.protobuf.ListValue));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.training.TrainingMetadata} returns this
 */
proto.training.TrainingMetadata.prototype.clearTrainingmethodsMap = function() {
  this.getTrainingmethodsMap().clear();
  return this;};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.training.MethodMetadata.prototype.toObject = function(opt_includeInstance) {
  return proto.training.MethodMetadata.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.training.MethodMetadata} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.training.MethodMetadata.toObject = function(includeInstance, msg) {
  var f, obj = {
    defaultModelId: jspb.Message.getFieldWithDefault(msg, 50001, ""),
    maxModelsPerUser: jspb.Message.getFieldWithDefault(msg, 50002, 0),
    datasetMaxSizeMb: jspb.Message.getFieldWithDefault(msg, 50003, 0),
    datasetMaxCountFiles: jspb.Message.getFieldWithDefault(msg, 50004, 0),
    datasetMaxSizeSingleFileMb: jspb.Message.getFieldWithDefault(msg, 50005, 0),
    datasetFilesType: jspb.Message.getFieldWithDefault(msg, 50006, ""),
    datasetType: jspb.Message.getFieldWithDefault(msg, 50007, ""),
    datasetDescription: jspb.Message.getFieldWithDefault(msg, 50008, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.training.MethodMetadata}
 */
proto.training.MethodMetadata.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.training.MethodMetadata;
  return proto.training.MethodMetadata.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.training.MethodMetadata} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.training.MethodMetadata}
 */
proto.training.MethodMetadata.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 50001:
      var value = /** @type {string} */ (reader.readString());
      msg.setDefaultModelId(value);
      break;
    case 50002:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setMaxModelsPerUser(value);
      break;
    case 50003:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDatasetMaxSizeMb(value);
      break;
    case 50004:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDatasetMaxCountFiles(value);
      break;
    case 50005:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDatasetMaxSizeSingleFileMb(value);
      break;
    case 50006:
      var value = /** @type {string} */ (reader.readString());
      msg.setDatasetFilesType(value);
      break;
    case 50007:
      var value = /** @type {string} */ (reader.readString());
      msg.setDatasetType(value);
      break;
    case 50008:
      var value = /** @type {string} */ (reader.readString());
      msg.setDatasetDescription(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.training.MethodMetadata.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.training.MethodMetadata.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.training.MethodMetadata} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.training.MethodMetadata.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDefaultModelId();
  if (f.length > 0) {
    writer.writeString(
      50001,
      f
    );
  }
  f = message.getMaxModelsPerUser();
  if (f !== 0) {
    writer.writeUint64(
      50002,
      f
    );
  }
  f = message.getDatasetMaxSizeMb();
  if (f !== 0) {
    writer.writeUint64(
      50003,
      f
    );
  }
  f = message.getDatasetMaxCountFiles();
  if (f !== 0) {
    writer.writeUint64(
      50004,
      f
    );
  }
  f = message.getDatasetMaxSizeSingleFileMb();
  if (f !== 0) {
    writer.writeUint64(
      50005,
      f
    );
  }
  f = message.getDatasetFilesType();
  if (f.length > 0) {
    writer.writeString(
      50006,
      f
    );
  }
  f = message.getDatasetType();
  if (f.length > 0) {
    writer.writeString(
      50007,
      f
    );
  }
  f = message.getDatasetDescription();
  if (f.length > 0) {
    writer.writeString(
      50008,
      f
    );
  }
};


/**
 * optional string default_model_id = 50001;
 * @return {string}
 */
proto.training.MethodMetadata.prototype.getDefaultModelId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 50001, ""));
};


/**
 * @param {string} value
 * @return {!proto.training.MethodMetadata} returns this
 */
proto.training.MethodMetadata.prototype.setDefaultModelId = function(value) {
  return jspb.Message.setProto3StringField(this, 50001, value);
};


/**
 * optional uint64 max_models_per_user = 50002;
 * @return {number}
 */
proto.training.MethodMetadata.prototype.getMaxModelsPerUser = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 50002, 0));
};


/**
 * @param {number} value
 * @return {!proto.training.MethodMetadata} returns this
 */
proto.training.MethodMetadata.prototype.setMaxModelsPerUser = function(value) {
  return jspb.Message.setProto3IntField(this, 50002, value);
};


/**
 * optional uint64 dataset_max_size_mb = 50003;
 * @return {number}
 */
proto.training.MethodMetadata.prototype.getDatasetMaxSizeMb = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 50003, 0));
};


/**
 * @param {number} value
 * @return {!proto.training.MethodMetadata} returns this
 */
proto.training.MethodMetadata.prototype.setDatasetMaxSizeMb = function(value) {
  return jspb.Message.setProto3IntField(this, 50003, value);
};


/**
 * optional uint64 dataset_max_count_files = 50004;
 * @return {number}
 */
proto.training.MethodMetadata.prototype.getDatasetMaxCountFiles = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 50004, 0));
};


/**
 * @param {number} value
 * @return {!proto.training.MethodMetadata} returns this
 */
proto.training.MethodMetadata.prototype.setDatasetMaxCountFiles = function(value) {
  return jspb.Message.setProto3IntField(this, 50004, value);
};


/**
 * optional uint64 dataset_max_size_single_file_mb = 50005;
 * @return {number}
 */
proto.training.MethodMetadata.prototype.getDatasetMaxSizeSingleFileMb = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 50005, 0));
};


/**
 * @param {number} value
 * @return {!proto.training.MethodMetadata} returns this
 */
proto.training.MethodMetadata.prototype.setDatasetMaxSizeSingleFileMb = function(value) {
  return jspb.Message.setProto3IntField(this, 50005, value);
};


/**
 * optional string dataset_files_type = 50006;
 * @return {string}
 */
proto.training.MethodMetadata.prototype.getDatasetFilesType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 50006, ""));
};


/**
 * @param {string} value
 * @return {!proto.training.MethodMetadata} returns this
 */
proto.training.MethodMetadata.prototype.setDatasetFilesType = function(value) {
  return jspb.Message.setProto3StringField(this, 50006, value);
};


/**
 * optional string dataset_type = 50007;
 * @return {string}
 */
proto.training.MethodMetadata.prototype.getDatasetType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 50007, ""));
};


/**
 * @param {string} value
 * @return {!proto.training.MethodMetadata} returns this
 */
proto.training.MethodMetadata.prototype.setDatasetType = function(value) {
  return jspb.Message.setProto3StringField(this, 50007, value);
};


/**
 * optional string dataset_description = 50008;
 * @return {string}
 */
proto.training.MethodMetadata.prototype.getDatasetDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 50008, ""));
};


/**
 * @param {string} value
 * @return {!proto.training.MethodMetadata} returns this
 */
proto.training.MethodMetadata.prototype.setDatasetDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 50008, value);
};


goog.object.extend(exports, proto.training);
