// @generated by protoc-gen-es v1.6.0 with parameter "target=js"
// @generated from file token_service.proto (package escrow, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * TokenRequest is a request for getting a valid token.
 *
 * @generated from message escrow.TokenRequest
 */
export const TokenRequest = proto3.makeMessageType(
  "escrow.TokenRequest",
  () => [
    { no: 1, name: "channel_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "current_nonce", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "signed_amount", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "signature", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 5, name: "current_block", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 6, name: "claim_signature", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * TokenReply message contains a latest channel state. current_nonce and
 *
 * @generated from message escrow.TokenReply
 */
export const TokenReply = proto3.makeMessageType(
  "escrow.TokenReply",
  () => [
    { no: 1, name: "channel_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "planned_amount", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "used_amount", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ],
);

