import MPEAbi from 'singularitynet-platform-contracts/abi/MultiPartyEscrow';
import MPENetworks from 'singularitynet-platform-contracts/networks/MultiPartyEscrow';
import { map } from 'lodash';

import PaymentChannel from './PaymentChannel';
import logger from '../utils/logger';

class MPEContract {
  /**
   * @param {Web3} web3
   * @param {number} networkId
   */
  constructor(web3, networkId) {
    this._web3 = web3;
    this._networkId = networkId;
    this._contract = this._web3.eth.Contract(MPEAbi, MPENetworks[networkId].address);
  }

  /**
   * An instance of Multi Party Contract generated by Web3
   * @type {Contract}
   * @see {@link https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html|Web3 Contract}
   */
  get contract() {
    return this._contract;
  }

  /**
   * The public address of the MPE account
   * @type {string}
   */
  get address() {
    return this.contract.address;
  }

  /**
   * Returns the balance against the address in Multi Party Escrow Account
   * @param {string} address - The public address of account
   * @returns {Promise<BigNumber>}
   */
  async balance(address) {
    logger.debug('Fetching MPE account balance', { tags: ['MPE'] });
    return this.contract.methods.balances(address).call()
  }

  /**
   * Transfers tokens from the account to MPE account
   * @param {Account} account - The account from which the tokens needs to be transferred.
   * @param {BigNumber} amountInCogs - The amount to transfer in cogs
   * @returns {Promise.<TransactionReceipt>}
   */
  async deposit(account, amountInCogs) {
    logger.info(`Depositing ${amountInCogs}cogs to MPE account`, { tags: ['MPE'] });
    const depositOperation = this.contract.methods.deposit;
    return account.sendTransaction(this.address, depositOperation, amountInCogs);
  }

  /**
   * Withdraws tokens from MPE account and deposits to the account
   * @param {Account} account - The account to deposit tokens
   * @param {BigNumber} amountInCogs - The amount to be withdrawn
   * @returns {Promise.<TransactionReceipt>}
   */
  async withdraw(account, amountInCogs) {
    logger.info(`Withdrawing ${amountInCogs}cogs from MPE account`, { tags: ['MPE'] });
    const withdrawOperation = this.contract.methods.withdraw;
    return account.sendTransaction(this.address, withdrawOperation, amountInCogs);
  }

  /**
   * Opens a payment channel between an account and the given service with the specified tokens and expiration period
   * @param {Account} account - The account to create payment channel for
   * @param {ServiceClient} service - The AI service between which the payment channel needs to be opened
   * @param {BigNumber} amount - The initial tokens with the which payment channel needs to be opened
   * @param {BigNumber} expiration - The expiry of the payment channel in terms of block number
   * @returns {Promise.<TransactionReceipt>}
   */
  async openChannel(account, service, amount, expiration) {
    const {
      payment_address: recipientAddress,
      group_id_in_bytes: groupId
    } = service.group;

    logger.info(`Opening new payment channel [amount: ${amount}, expiration: ${expiration}]`, { tags: ['MPE'] });
    const openChannelOperation = this.contract.methods.openChannel;
    const openChannelFnArgs = [account.signerAddress, recipientAddress, groupId, amount, expiration];
    return account.sendTransaction(this.address, openChannelOperation, ...openChannelFnArgs);
  }

  /**
   * Deposits the specified tokens to MPE Account and opens a payment channel between an account and the given service
   * with the specified tokens and expiration period
   * @param {Account} account - The account against which the operations needs to be performed
   * @param {ServiceClient} service - The AI service between which the payment channel needs to be opened
   * @param {BigNumber} amount - The initial tokens with the which payment channel needs to be opened
   * @param {BigNumber} expiration - The expiry of the payment channel in terms of block number
   * @returns {Promise.<TransactionReceipt>}
   */
  async depositAndOpenChannel(account, service, amount, expiration) {
    const {
      payment_address: recipientAddress,
      group_id_in_bytes: groupId
    } = service.group;
    const alreadyApprovedAmount = await account.allowance();
    if(amount > alreadyApprovedAmount) {
      await account.approveTransfer(amount);
    }

    const depositAndOpenChannelOperation = this.contract.methods.depositAndOpenChannel;
    const operationArgs = [account.signerAddress, recipientAddress, groupId, amount, expiration];
    logger.info(`Depositing ${amount}cogs to MPE address and Opening new payment channel [expiration: ${expiration}]`, { tags: ['MPE'] });
    return account.sendTransaction(this.address, depositAndOpenChannelOperation, ...operationArgs);
  }

  /**
   * Funds an existing payment channel
   * @param {Account} account - The account against which the operations needs to be performed
   * @param {BigNumber} channelId - The payment channel id
   * @param {BigNumber} amount - The number of tokens to fund the channel
   * @returns {Promise.<TransactionReceipt>}
   */
  async channelAddFunds(account, channelId, amount) {
    await this._fundEscrowAccount(account, amount);

    logger.info(`Funding PaymentChannel[id: ${channelId}] with ${amount}cogs`, { tags: ['MPE'] });
    const channelAddFundsOperation = this.contract.methods.channelAddFunds;
    return account.sendTransaction(this.address, channelAddFundsOperation, channelId, amount);
  }

  /**
   * Extends an existing payment channel
   * @param {Account} account - The account against which the operations needs to be performed
   * @param {BigNumber} channelId - The payment channel id
   * @param {BigNumber} expiration - The expiry in terms of block number to extend the channel
   * @returns {Promise.<TransactionReceipt>}
   */
  async channelExtend(account, channelId, expiration) {
    logger.info(`Extending PaymentChannel[id: ${channelId}]. New expiry is block# ${expiration}`, { tags: ['MPE'] });
    const channelExtendOperation = this.contract.methods.channelExtend;
    return account.sendTransaction(this.address, channelExtendOperation, channelId, expiration);
  }

  /**
   * Extends and adds funds to an existing payment channel
   * @param {Account} account - The account against which the operations needs to be performed
   * @param {BigNumber} channelId - The payment channel id
   * @param {BigNumber} expiration - The expiry in terms of block number to extend the channel
   * @param {BigNumber} amount - The number of tokens to fund the channel
   * @returns {Promise.<TransactionReceipt>}
   */
  async channelExtendAndAddFunds(account, channelId, expiration, amount) {
    await this._fundEscrowAccount(account, amount);

    logger.info(`Extending and Funding PaymentChannel[id: ${channelId}] with amount: ${amount} and expiry: ${expiration}`, { tags: ['MPE'] });
    const channelExtendAndAddFundsOperation = this.contract.methods.channelExtendAndAddFunds;
    return account.sendTransaction(this.address, channelExtendAndAddFundsOperation, channelId, expiration, amount);
  }

  /**
   * Fetches the latest state of the payment channel
   * @param {BigNumber} channelId - The payment channel id
   * @returns {Promise<any>} - The return value(s) of the smart contract method. If it returns a single value, it’s returned as is. If it has multiple return values they are returned as an object with properties and indices:
   */
  async channels(channelId) {
    logger.debug(`Fetch latest PaymentChannel[id: ${channelId}] state`, { tags: ['MPE'] });
    return this.contract.methods.channels(channelId).call();
  }

  /**
   * Fetches all the payment channels opened between the account and the service starting from the given block number
   * @param {Account} account
   * @param {ServiceClient} service
   * @param {number} [startingBlockNumber=MPE Contract deployment block number] - The starting block number to fetch the
   * open channels from
   * @returns {Promise.<PaymentChannel[]>}
   */
  async getPastOpenChannels(account, service, startingBlockNumber) {
    const fromBlock = startingBlockNumber ? startingBlockNumber : await this._deploymentBlockNumber();
    logger.debug(`Fetching all payment channel open events starting at block: ${fromBlock}`, { tags: ['MPE'] });
    const options = {
      filter: {
        sender: account.address,
        recipient: service.group.payment_address,
        groupId: service.group.group_id_in_bytes,
      },
      fromBlock,
      toBlock: 'latest'
    };
    const channelsOpened = await this.contract.getPastEvents('ChannelOpen', options);
    return map(channelsOpened, channelOpenEvent => {
      const channelId = channelOpenEvent.returnValues.channelId;
      return new PaymentChannel(channelId, this._web3, account, service, this);
    });
  }

  async _fundEscrowAccount(account, amount) {
    const currentEscrowBalance = await this.balance(account.address);
    if(amount > currentEscrowBalance) {
      await account.depositToEscrowAccount(amount - currentEscrowBalance);
    }
  }

  async _deploymentBlockNumber() {
    const { transactionHash } = MPENetworks[this._networkId];
    const { blockNumber } = await this._web3.eth.getTransactionReceipt(transactionHash);
    return blockNumber;
  }
}

export default MPEContract;
